title: lo.calho.st
author: Travis Mick 
description: ""

author:
  name: Travis Mick
social-network-links:
  github: tmick0
navbar-links:
  Publications: publications
  Projects: projects
  About: about

encoding: utf-8
lang: en-US
timezone: America/Denver

plugins:
 - jekyll-paginate

show_excerpts: true
excerpt_length: 300
excerpt_separator: <!-- more -->
title-separator: "-"
date_format: "%B %-d, %Y"
  
navbar-col: "#404040"
navbar-text-col: "#a0a0a0"
navbar-children-col: "#F5F5F5"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#7bc9f1"
footer-col: "#404040"
footer-text-col: "#e0e0e0"
footer-link-col: "#a0a0a0"
  
markdown: kramdown

permalink: /posts/:title/
paginate: 5
paginate_path: /page-:num


defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
      social-share: false
  - scope:
      path: ""
    values:
      layout: "page"
      show-avatar: false

exclude:
- Gemfile
- Gemfile.lock
- .jekyll-cache
- CNAME

